services:
  llm:
    build: ./llm
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  cowrie:
    build: ./cowrie
    ports:
      - "2222:2222"
    volumes:
      - ./logs:/cowrie/var/log
    environment:
      - LLM_API=http://llm:8000/respond
    depends_on:
      llm:
        condition: service_healthy
    restart: unless-stopped